### ISSUE TITLE
cann't get the full overview of this project.

### ISSUE THREAD

**Issue by MdAkdas** [manjurulhoque/django-resume-app#1]
can you give screenshot or live demo for this project.

**Comment by manjurulhoque** [comment]
Clone the project and run yourself. You will find it.

**Comment by MdAkdas** [comment]
![Screenshot from 2020-03-18 16-41-17](https://user-images.githubusercontent.com/43089126/76955007-66fa0300-6937-11ea-88b8-699fd322aca2.png)

can you tell me what would be the error here?

**Comment by manjurulhoque** [comment]
Actually, it's not error. Maybe I printed a variable in template.
